### ISSUE TITLE
Ability Check Error

### ISSUE THREAD

**Issue by mcstalker** [mlenser/roll20-character-sheets#125] opened 2016-05-02 03:50 UTC
When you use an ability check for an ability that had a +0 from your ability score and a +1 from the cog page Bonuses & Penitents section the result is always 0.

I think the problem is in bold below.  The two plus signs cause an error.  Normally the string would have the ability score modifier in between the pluses but for some reason when the ability score modifier is 0 it adds nothing.

@{Bunn Blackdust|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Bunn Blackdust|character_name}}} @{Bunn Blackdust|show_character_name} {{title=Arcana (Int)}} {{subheader=Ability Check}} @{Bunn Blackdust|roll_info} {{roll1=[[@{Bunn Blackdust|preroll}d20@{Bunn Blackdust|postroll}@{Bunn Blackdust|d20_mod} **_+  +_** (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|roll_setting}@{Bunn Blackdust|d20_mod} **_+  +_** (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|attacher_skill}

**Comment by mlenser** [comment] 2016-05-02 08:19
Do not add a plus symbol on the bonuses page and the problem goes away.

I would restrict it to numbers only, but things like bless add 1d4 so I can't.

**Comment by mcstalker** [comment] 2016-05-02 14:03
I didn't the plus symbol is their all of the time.  

Michael Stalker

**Comment by mlenser** [comment] 2016-05-02 14:25
Can you send me a screenshot of your setting tab

**Comment by mcstalker** [comment] 2016-05-02 14:27
Here is the string from a new character sheet with no changes made.

@{Liw Braoketo|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Liw Braoketo|character_name}}} @{Liw Braoketo|show_character_name} {{title=Acrobatics (Dex)}} {{subheader=Ability Check}} @{Liw Braoketo|roll_info} {{roll1=[[@{Liw Braoketo|preroll}d20@{Liw Braoketo|postroll}@{Liw Braoketo|d20_mod} + ]]}} @{Liw Braoketo|roll_setting}@{Liw Braoketo|d20_mod} + ]]}} @{Liw Braoketo|attacher_skill}

I have only made the following change the the character:

![image](https://cloud.githubusercontent.com/assets/19143557/14956880/a2e2d790-1047-11e6-834f-ae8a98b4e451.png)

Here is the new string: (notice the **_ +  + _**)

@{Liw Braoketo|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Liw Braoketo|character_name}}} @{Liw Braoketo|show_character_name} {{title=Acrobatics (Dex)}} {{subheader=Ability Check}} @{Liw Braoketo|roll_info} {{roll1=[[@{Liw Braoketo|preroll}d20@{Liw Braoketo|postroll}@{Liw Braoketo|d20_mod}**_ +  + _**(@{Liw Braoketo|global_check_bonus})[global check bonus]]]}} @{Liw Braoketo|roll_setting}@{Liw Braoketo|d20_mod}**_ +  + _**(@{Liw Braoketo|global_check_bonus})[global check bonus]]]}} @{Liw Braoketo|attacher_skill}

**Comment by mlenser** [comment] 2016-05-02 14:27
Ah, I expected it to be "+1" as that is what has caused it in the past.

I will investigate. Thanks for the report!

**Comment by mcstalker** [comment] 2016-05-02 14:31
I think the problem is the ability modifier is being removed with it is set to 0.  

Here is the string with a dex modifier of +1.  The **_1[dex]_** is now in between the **+ +** 

@{Liw Braoketo|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Liw Braoketo|character_name}}} @{Liw Braoketo|show_character_name} {{title=Acrobatics (Dex)}} {{subheader=Ability Check}} @{Liw Braoketo|roll_info} {{roll1=[[@{Liw Braoketo|preroll}d20@{Liw Braoketo|postroll}@{Liw Braoketo|d20_mod}**_ + 1[dex] + _**(@{Liw Braoketo|global_check_bonus})[global check bonus]]]}} @{Liw Braoketo|roll_setting}@{Liw Braoketo|d20_mod_**} + 1[dex] + **_(@{Liw Braoketo|global_check_bonus})[global check bonus]]]}} @{Liw Braoketo|attacher_skill}

**Comment by mlenser** [comment] 2016-05-02 16:41
Can you please provide steps to reproduce this? I cannot reproduce it.

Are you on the latest version? 3.1.1?

This is the output I get

@{Example|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Example|character_name}}} @{Example|show_character_name} {{title=Acrobatics (Dex)}} {{subheader=Ability Check}} @{Example|roll_info} {{roll1=[[@{Example|preroll}d20@{Example|postroll}@{Example|d20_mod} + 7[proficient] + (@{Example|global_check_bonus})[global check bonus]]]}} @{Example|roll_setting}@{Example|d20_mod} + 7[proficient] + (@{Example|global_check_bonus})[global check bonus]]]}} @{Example|attacher_skill}

**Comment by mcstalker** [comment] 2016-05-02 17:16
I am using version 2.4.13.

**Comment by mlenser** [comment] 2016-05-02 17:17
Please update and check or join my test campaign and verify there.

Test campaign: https://app.roll20.net/join/1206379/qP-T_Q

**Comment by mcstalker** [comment] 2016-05-04 04:56
I have tested in 3.1.2 and I see the same problem.

- Create a new character.
- Move to the character sheet tab
- Click on cog
- Set global_check_bonus as below

![image](https://cloud.githubusercontent.com/assets/19143557/14956880/a2e2d790-1047-11e6-834f-ae8a98b4e451.png)

- go to core
- click any skill

The problem only seems to happen when you ability_mod=0, proficient=false, global_check_bonus > 0

The following does not work with (ability_mod=0, proficient=false, global_check_bonus=1)

@{Bunn Blackdust|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Bunn Blackdust|character_name}}} @{Bunn Blackdust|show_character_name} {{title=Nature (Int)}} {{subheader=Ability Check}} @{Bunn Blackdust|roll_info} {{roll1=[[@{Bunn Blackdust|preroll}d20@{Bunn Blackdust|postroll}@{Bunn Blackdust|d20_mod} **+  +** (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|roll_setting}@{Bunn Blackdust|d20_mod} +  + (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|attacher_skill}

The following works with (ability_mod=0, proficient=**true**, global_check_bonus=1)

@{Bunn Blackdust|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Bunn Blackdust|character_name}}} @{Bunn Blackdust|show_character_name} {{title=Nature (Int)}} {{subheader=Ability Check}} @{Bunn Blackdust|roll_info} {{roll1=[[@{Bunn Blackdust|preroll}d20@{Bunn Blackdust|postroll}@{Bunn Blackdust|d20_mod} **+ 4[proficient] +** (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|roll_setting}@{Bunn Blackdust|d20_mod} + 4[proficient] + (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|attacher_skill}

The following works with (ability_mod=**1**, proficient=false, global_check_bonus=1)

@{Bunn Blackdust|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Bunn Blackdust|character_name}}} @{Bunn Blackdust|show_character_name} {{title=Nature (Int)}} {{subheader=Ability Check}} @{Bunn Blackdust|roll_info} {{roll1=[[@{Bunn Blackdust|preroll}d20@{Bunn Blackdust|postroll}@{Bunn Blackdust|d20_mod} **+ 1[int] +** (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|roll_setting}@{Bunn Blackdust|d20_mod} + 1[int] + (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|attacher_skill}

The following works with (ability_mod=**1**, proficient=**true**, global_check_bonus=1)

@{Bunn Blackdust|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Bunn Blackdust|character_name}}} @{Bunn Blackdust|show_character_name} {{title=Nature (Int)}} {{subheader=Ability Check}} @{Bunn Blackdust|roll_info} {{roll1=[[@{Bunn Blackdust|preroll}d20@{Bunn Blackdust|postroll}@{Bunn Blackdust|d20_mod} + **4[proficient] + 1[int] +** (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|roll_setting}@{Bunn Blackdust|d20_mod} + 4[proficient] + 1[int] + (@{Bunn Blackdust|global_check_bonus})[global check bonus]]]}} @{Bunn Blackdust|attacher_skill}

The following works with (ability_mod=0, proficient=false, global_check_bonus=0)

I think the problem is in bold below:

@{Bunn Blackdust|output_option} &{template:5e-shaped} {{ability=1}} {{character_name=@{Bunn Blackdust|character_name}}} @{Bunn Blackdust|show_character_name} {{title=Nature (Int)}} {{subheader=Ability Check}} @{Bunn Blackdust|roll_info} {{roll1=[[@{Bunn Blackdust|preroll}d20@{Bunn Blackdust|postroll}@{Bunn Blackdust|d20_mod} **+** ]]}} @{Bunn Blackdust|roll_setting}@{Bunn Blackdust|d20_mod} **+** ]]}} @{Bunn Blackdust|attacher_skill}

The plus sign should not be at the end of the roll1.  It is assuming the ability_mod will succeed it but when ability_mod  is 0 it is dropped from the line.

**Comment by mcstalker** [comment] 2016-05-04 06:31
look at 5eShaped\precompiled\components\sheetWorkers.js(3553):

        const globalCheckBonus = v.global_check_bonus;
        if (exists(globalCheckBonus)) {
          if (!isNaN(globalCheckBonus)) {
            total += getIntValue(globalCheckBonus);
          }
          totalFormula += ' + (@{global_check_bonus})[global check bonus]';
        }

I think you need to remove the + sign or check it totalFormula not '' then add the ' + '

        const globalCheckBonus = v.global_check_bonus;
        if (exists(globalCheckBonus)) {
          if (!isNaN(globalCheckBonus)) {
            total += getIntValue(globalCheckBonus);
          }
          if (!totalFormula = '') { 
                     totalFormula += ' + '; 
          } 
          totalFormula += '(@{global_check_bonus})[global check bonus]';
        }

**Comment by mlenser** [comment] 2016-05-04 20:53
This should be fixed in 3.1.3. Please let me know if it isn't.

**Closed by mlenser** 2016-05-04 20:53 UTC
